list: $/kevinlyh/user/models/user/columns.yaml
modelClass: Kevinlyh\User\Models\User
title: Users
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'kevinlyh/user/users/update/:id'
